#!/usr/bin/env ansible-playbook -i localhost, -v
---
- name: sample playbook
  hosts: localhost
  gather_facts: no
  vars:
      ansible_connection: local
  tasks:

    - name: "This is the sample task name"
      shell: |
         echo -e "aaa\nbbb"
         echo -e "ccc\nddd" >&2
